name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  actions: read

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install and Build 🔧
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.4.0
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies 📦
        run: npm ci

      - name: Build project 🏗️
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@6c2e9a5a25b27bce1b5bb14e8e9cb9acd45f62f0 # v4.7.3
        with:
          folder: dist
          branch: gh-pages
